#!/bin/bash

if [ -z "${ASSET_URL_PREFIX}" ]; then
  echo "The ASSET_URL_PREFIX environment variable needs to be set to continue (eg: 'ASSET_URL_PREFIX=https://s3-eu-west-1.amazonaws.com')"
  exit 1
fi

# ASSET_BUCKET_NAME is an empty string if we aren't actually talking to S3
if [ -z "${ASSET_BUCKET_NAME}" ]; then
  export ASSET_FRAGMENT_PATH=""
else
  export ASSET_FRAGMENT_PATH="/${ASSET_BUCKET_NAME}"
fi

cat /etc/nginx/conf.d-templates/default-server.conf.template      \
  | sed -e "s#\${ASSET_FRAGMENT_PATH}#${ASSET_FRAGMENT_PATH}#g"       \
  | sed -e "s#\${ASSET_URL_PREFIX}#${ASSET_URL_PREFIX}#g"         \
  > /etc/nginx/conf.d/default-server.conf

exec nginx -g "daemon off;"
